// Root layout component for the Next.js application
// This component wraps all pages and provides the basic HTML structure,
// fonts, global styles, and common layout elements like header and footer

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/Sections/Header";
import Footer from "@/components/Sections/Footer";

// Load Geist Sans font for general UI text
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable name for the font
  subsets: ["latin"], // Only load Latin characters for better performance
});

// Load Geist Mono font for code and monospace text
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the application (used by Next.js for SEO, etc.)
export const metadata: Metadata = {
  title: "AI Reviewer", // Page title
  description: "Generated by create next app", // Page description
  icons: {
    icon: "/lightbulb.png", // Favicon
  },
};

// Root layout component that wraps all pages
export default function RootLayout({
  children, // The page content to be rendered
}: Readonly<{
  children: React.ReactNode; // TypeScript type for React children
}>) {
  return (
    // HTML document structure
    <html
      lang="en" // Language attribute for accessibility
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} // Apply font variables and styling
    >
      <body className="min-h-full flex flex-col"> {/* Full height flexbox layout */}
        <Header /> {/* Site header component */}
        {children} {/* Page-specific content */}
        <Footer /> {/* Site footer component */}
      </body>
    </html>
  );
}
